---
name: Remove docker images from local system
command: docker rmi {{image_ids}}
tags:
  - docker
description: Remove docker images currently stored on your system
arguments: 
  - name: image_id
      description: "This image ID can be found by using the `docker images ls` command"
source_url: "https://docs.docker.com/engine/reference/commandline/rmi/"
author: guel-codes
author_url: "https://github.com/guel-codes"
shells: 
